/*----------------------------------------------------------------------
Compiler Generator Coco/R,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
ported to C++ by Csaba Balazs, University of Szeged
with improvements by Pat Terry, Rhodes University

This program is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation; either version 2, or (at your option) any 
later version.

This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
for more details.

You should have received a copy of the GNU General Public License along 
with this program; if not, write to the Free Software Foundation, Inc., 
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than 
Coco/R itself) does not fall under the GNU General Public License.
-----------------------------------------------------------------------*/


#if !defined(COCO_PARSER_H__)
#define COCO_PARSER_H__



#include "Scanner.h"



class Errors {
public:
	int count;			// number of errors detected

	Errors();
	void SynErr(int line, int col, int n);
	void Error(int line, int col, const wchar_t *s);
	void Warning(int line, int col, const wchar_t *s);
	void Warning(const wchar_t *s);
	void Exception(const wchar_t *s);

}; // Errors

class Parser {
private:
	enum {
		_EOF=0,
		_assign=1,
		_condition_eq=2,
		_bang_equal=3,
		_less=4,
		_less_equal=5,
		_greater=6,
		_greater_equal=7,
		_semi=8,
		_open_paren=9,
		_close_paren=10,
		_open_scope=11,
		_close_scope=12,
		_plus=13,
		_minus=14,
		_star=15,
		_slash=16,
		_percent=17,
		_logical_and=18,
		_logical_or=19,
		_logical_not=20,
		_identifier=21,
		_int_lit=22
	};
	int maxT;

	Token *dummyToken;
	int errDist;
	int minErrDist;

	void SynErr(int n);
	void Get();
	void Expect(int n);
	bool StartOf(int s);
	void ExpectWeak(int n, int follow);
	bool WeakSeparator(int n, int syFol, int repFol);

public:
	Scanner *scanner;
	Errors  *errors;

	Token *t;			// last recognized token
	Token *la;			// lookahead token

(. 
#include "../src/ast.h"
#include "../src/arena.h"

#include <string>
#include <stdexcept>
#include <cwchar>
#include <utility>

//
// The generated Coco/R parser will build the AST through these.
//
// main() will set:
//
//     arena = &myArena;
//
// before calling:
//
//     parser.Nex();
//

ArenaAllocator *arena = nullptr;
NodeProgram program;

static std::string token_string(Token *token)
{
    if (!token || !token->val)
        return {};

    std::wstring wide(token->val);

    return std::string(
        wide.begin(),
        wide.end()
    );
}

static NodeExpr *make_int_expr(const std::string &value)
{
    if (!arena)
        throw std::runtime_error("Nex parser arena is not initialized");

    NodeExpr *expr = arena->alloc<NodeExpr>();

    if (!expr)
        throw std::bad_alloc{};

    NodeExprIntLit node{
        value
    };

    return new(expr) NodeExpr{
        node
    };
}

static NodeExpr *make_identifier_expr(const std::string &value)
{
    if (!arena)
        throw std::runtime_error("Nex parser arena is not initialized");

    NodeExpr *expr = arena->alloc<NodeExpr>();

    if (!expr)
        throw std::bad_alloc{};

    NodeExprIdentifier node{
        value
    };

    return new(expr) NodeExpr{
        node
    };
}

static NodeExpr *make_binary_expr(
    NodeExpr *left,
    const std::string &op,
    NodeExpr *right
)
{
    if (!arena)
        throw std::runtime_error("Nex parser arena is not initialized");

    BinaryExpr *binary = arena->alloc<BinaryExpr>();

    if (!binary)
        throw std::bad_alloc{};

    new(binary) BinaryExpr{
        left,
        op,
        right
    };

    NodeExpr *expr = arena->alloc<NodeExpr>();

    if (!expr)
        throw std::bad_alloc{};

    return new(expr) NodeExpr{
        binary
    };
}

static NodeExpr *make_unary_expr(
    const std::string &op,
    NodeExpr *operand
)
{
    if (!arena)
        throw std::runtime_error("Nex parser arena is not initialized");

    UnaryExpr *unary = arena->alloc<UnaryExpr>();

    if (!unary)
        throw std::bad_alloc{};

    new(unary) UnaryExpr{
        op,
        operand
    };

    NodeExpr *expr = arena->alloc<NodeExpr>();

    if (!expr)
        throw std::bad_alloc{};

    return new(expr) NodeExpr{
        unary
    };
}

static NodeScope *make_scope()
{
    if (!arena)
        throw std::runtime_error("Nex parser arena is not initialized");

    NodeScope *scope = arena->alloc<NodeScope>();

    if (!scope)
        throw std::bad_alloc{};

    return new(scope) NodeScope{};
}

static NodeStmnt *make_statement()
{
    if (!arena)
        throw std::runtime_error("Nex parser arena is not initialized");

    NodeStmnt *statement = arena->alloc<NodeStmnt>();

    if (!statement)
        throw std::bad_alloc{};

    return statement;
}

static NodeStmnt *make_let(
    const std::string &identifier,
    NodeExpr *expr
)
{
    NodeStmnt *statement = make_statement();

    return new(statement) NodeStmnt{
        NodeStmntLet{
            identifier,
            expr
        }
    };
}

static NodeStmnt *make_assign(
    const std::string &identifier,
    NodeExpr *expr
)
{
    NodeStmnt *statement = make_statement();

    return new(statement) NodeStmnt{
        NodeStmntAssign{
            identifier,
            expr
        }
    };
}

static NodeStmnt *make_exit(NodeExpr *expr)
{
    NodeStmnt *statement = make_statement();

    return new(statement) NodeStmnt{
        NodeStmntExit{
            expr
        }
    };
}

static NodeStmnt *make_scope_statement(NodeScope *scope)
{
    NodeStmnt *statement = make_statement();

    return new(statement) NodeStmnt{
        scope
    };
}

static NodeStmnt *make_if(
    NodeExpr *condition,
    NodeScope *scope,
    NodeScope *else_scope,
    NodeStmntIf *else_if
)
{
    if (!arena)
        throw std::runtime_error("Nex parser arena is not initialized");

    NodeStmntIf *if_statement =
        arena->alloc<NodeStmntIf>();

    if (!if_statement)
        throw std::bad_alloc{};

    new(if_statement) NodeStmntIf{
        condition,
        scope,
        else_scope,
        else_if
    };

    NodeStmnt *statement = make_statement();

    return new(statement) NodeStmnt{
        if_statement
    };
}

static NodeStmntIf *get_if_statement(NodeStmnt *statement)
{
    if (!statement)
        throw std::runtime_error(
            "Expected if statement"
        );

    return std::get<NodeStmntIf *>(
        statement->stmnt
    );
}

static NodeStmnt *make_while(
    NodeExpr *condition,
    NodeScope *scope
)
{
    if (!arena)
        throw std::runtime_error("Nex parser arena is not initialized");

    NodeStmntWhile *while_statement =
        arena->alloc<NodeStmntWhile>();

    if (!while_statement)
        throw std::bad_alloc{};

    new(while_statement) NodeStmntWhile{
        condition,
        scope
    };

    NodeStmnt *statement = make_statement();

    return new(statement) NodeStmnt{
        while_statement
    };
}
.)



	Parser(Scanner *scanner);
	~Parser();
	void SemErr(const wchar_t* msg);

	void Nex();
	void Statement(out NodeStmnt *statement);
	void SetStmt(out NodeStmnt *statement);
	void ExitStmt(out NodeStmnt *statement);
	void IfStmt(out NodeStmnt *statement);
	void WhileStmt(out NodeStmnt *statement);
	void BlockStmt(out NodeStmnt *statement);
	void AssignStmt(out NodeStmnt *statement);
	void Expression(out NodeExpr *expr);
	void AndExpr(out NodeExpr *expr);
	void EqualityExpr(out NodeExpr *expr);
	void AddExpr(out NodeExpr *expr);
	void MultExpr(out NodeExpr *expr);
	void UnaryExpr(out NodeExpr *expr);
	void PrimaryExpr(out NodeExpr *expr);

	void Parse();

}; // end Parser



#endif

